version: '3.8'

services:
  # fastapi
  backend:
    container_name: backend
    build: .
    restart: always
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mongodb
  # postgres
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    expose:
      - 5432

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

#  bot:
#    build: .
#    restart: always
#    command: python src/bot.py

  celery_worker:
    build: .
    restart: always
    command: celery -A src.lib.celery.main.app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
